config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :proposals do
    resources :experiments do
      resources :observations
    end
  end

  # get '/proposals/:proposal_id' => 'proposals#show', as: 'proposal'
  get '/proposals/:proposal_id/experiments/:experiment_id' => 'experiments#show', as: 'experiment'


  post '/proposals/:proposal_id/comments' => 'comments#create', as: 'proposal_comments'
  post '/proposals/:proposal_id/experiments/:experiment_id/comments' => 'comments#create', as: 'experiment_comment'
  post '/proposals/:proposal_id/experiments/:experiment_id/observations/:observation_id/comments' => 'comments#create', as: 'observation_comment'

  get 'sessions/new'

  post 'sessions/create'

  get 'sessions/destroy'

  root 'proposals#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many  :comments, foreign_key: :commenter_id, as: :commentable
  has_many  :proposals, foreign_key: :faculty_id
  has_many  :experiments, foreign_key: :researcher_id
  has_many :observations, foreign_key: :researcher_id

  has_secure_password

  validates :name, presence: true, uniqueness: true, length: { maximum: 100 }
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:uft.)+edu)\z/i, :message => " is invalid. Make sure you register with a valid uft.edu email address."
  # validates :password, presence: true

  def is_faculty?
    self.role == "faculty" ? true : false
  end

  def is_researcher?
    self.role == "researcher" ? true : false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save && @user.valid?
      redirect_to "/"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
    @user = User.find(params[:id])
    @proposals = @user.proposals
    @experiments = @user.experiments
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :role)
  end
end

app/views/users/new.html.erb
<h1>User Registration</h1>

<%= form_for @user, url: users_path do |f| %>
  <%= render 'shared/error_messages' %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password, class: 'form-control' %>
  </p>
  <p>
    <%= f.radio_button(:role, "faculty") %>
    <%= label_tag(:role, "I am a faculty member") %>
    <%= f.radio_button(:role, "researcher") %>
    <%= label_tag(:role, "I am a lab researcher") %>
  </p>
  <p>
    <%= f.submit "Register", :class => "btn btn-primary" %>
  </p>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<h4><%= @user.role.capitalize %></h4>
<br>

<% if @user.is_faculty? %>
  <h3>Proposals: </h3>
<% else %>
  <h3>Experiments:</h3>
<% end %>
<br>

<% if @proposals %>
  <% @proposals.each do |proposal| %>
    <div class="container">
      <h3><%= link_to proposal.title, proposal_path(proposal) %></h3>

    <% if proposal.experiments %>
      <% proposal.experiments.each_with_index do |experiment, index| %>
      <div class='col-md-10'>
        <div class='panel-group'>
          <div class='panel'>
            <div class='panel-heading'>
              <h4 class='panel-title'>
                <a data-toggle='collapse' data-parent='.panel-group' href='#experiments<%= index %>'><%= experiment.title %></a>
              </h4>
            </div>
            <div id='experiments<%= index %>' class='panel-collapse collapse'>
              <div class='panel-body'>
                <div class="row">
                  <div class="col-md-2">
                    <h4>Title</h4>
                  </div>
                  <div class="col-md-10">
                    <p><%= experiment.title %></p>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-2">
                    <h4>Description</h4>
                  </div>
                  <div class="col-md-10">
                    <p><%= experiment.description %></p>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-2">
                    <h4>Equipment</h4>
                  </div>
                  <div class="col-md-10">
                    <p><%= experiment.equipment %></p>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-2">
                    <h4>Procedure</h4>
                  </div>
                  <div class="col-md-10">
                    <p><%= experiment.procedure %></p>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-2">
                    <h4>Results</h4>
                  </div>
                  <div class="col-md-10">
                    <p><%= experiment.results %></p>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-2">
                    <h4>Conclusion</h4>
                  </div>
                  <div class="col-md-10">
                    <p><%= experiment.conclusion %></p>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
  <% end %>
<% end %>

<% if @experiments %>
  <% @experiments.each_with_index do |exp, index| %>
    <div class='col-md-12'>
      <div class='panel-group'>
        <div class='panel'>
          <div class='panel-heading'>
            <h4 class='panel-title'>
              <a data-toggle='collapse' data-parent='.panel-group' href='#researcher_experiments<%= index %>'><%= exp.title %></a>
            </h4>
          </div>
          <div id='researcher_experiments<%= index %>' class='panel-collapse collapse'>
            <div class='panel-body'>
              <div class="row">
                <div class="col-md-2">
                  <h4>Proposal Title</h4>
                </div>
                <div class="col-md-10">
                  <p><%= exp.proposal.title %></p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-2">
                  <h4>Experiment Title</h4>
                </div>
                <div class="col-md-10">
                  <p><%= exp.title %></p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-2">
                  <h4>Description</h4>
                </div>
                <div class="col-md-10">
                  <p><%= exp.description %></p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-2">
                  <h4>Equipment</h4>
                </div>
                <div class="col-md-10">
                  <p><%= exp.equipment %></p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-2">
                  <h4>Procedure</h4>
                </div>
                <div class="col-md-10">
                  <p><%= exp.procedure %></p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-2">
                  <h4>Observations</h4>
                </div>
                <div class="col-md-10">
                  <p><%= exp.observations %></p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-2">
                  <h4>Results</h4>
                </div>
                <div class="col-md-10">
                  <p><%= exp.results %></p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-2">
                  <h4>Conclusion</h4>
                </div>
                <div class="col-md-10">
                  <p><%= exp.conclusion %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>