config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :proposals do
    resources :experiments do
      resources :observations
    end
  end

  # get '/proposals/:proposal_id' => 'proposals#show', as: 'proposal'
  get '/proposals/:proposal_id/experiments/:experiment_id' => 'experiments#show', as: 'experiment'


  post '/proposals/:proposal_id/comments' => 'comments#create', as: 'proposal_comments'
  post '/proposals/:proposal_id/experiments/:experiment_id/comments' => 'comments#create', as: 'experiment_comment'
  post '/proposals/:proposal_id/experiments/:experiment_id/observations/:observation_id/comments' => 'comments#create', as: 'observation_comment'

  get 'sessions/new'

  post 'sessions/create'

  get 'sessions/destroy'

  root 'proposals#index'

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  has_many    :comments, as: :commentable
  has_many :observations, foreign_key: :experiment_id
  belongs_to  :researcher, class_name: :User
  belongs_to  :proposal

  def current_stage
    if self.equipment == nil
      "equipment"
    elsif self.procedure == nil
      "procedure"
    elsif self.observations == nil
      "observations"
    elsif self.results == nil
      "results"
    else
      "conclusion"
    end
  end

  def progress
    if self.current_stage == "equipment"
      return 20
    elsif self.current_stage == "procedure"
      40
    elsif self.current_stage == "observations"
      60
    elsif self.current_stage == "results"
      80
    elsif self.current_stage == "conclusion"
      100
    end
  end

end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController

  before_filter :authorize
  before_filter :validate, :except => [:new, :create, :show]

  def new
    @user = User.find(session[:user_id])
    @proposal = Proposal.find(params[:proposal_id])
    @experiment = Experiment.new
    render :file => "/public/500.html",  :status => 500 unless @user.is_researcher?
  end

  def create
    @proposal = Proposal.find(params[:proposal_id])
    @experiment = @proposal.experiments.build(experiment_params)
      if @experiment.save
        redirect_to "/proposals/#{@proposal.id}/experiments/#{@experiment.id}"
      else
        render 'new'
      end
  end

  def show
    @user = User.find(session[:user_id])
    @proposal = Proposal.find(params[:proposal_id])
    @experiment = Experiment.includes(:comments).find(params[:id])
    @equipment_comments = @experiment.comments.equipment
    @procedure_comments = @experiment.comments.procedure
    @results_comments = @experiment.comments.results
    @conclusion_comments = @experiment.comments.conclusion
    @observation = Observation.new
    @observations = @experiment.observations
    @comment = Comment.new
    render :file => "/public/500.html",  :status => 500 unless owns_experiment? || session[:user_id] == @proposal.faculty_id
  end

  def edit
    @experiment = Experiment.find(params[:id])
  end

  def update
    @experiment = Experiment.find(params[:id])
    if @experiment.update(experiment_params)
      redirect_to proposal_experiment_path
    else
      render 'edit'
    end
  end

  def destroy
    @experiment = Experiment.find(params[:id])
    @proposal = @experiment.proposal
    @experiment.destroy
    redirect_to @proposal
  end

  private

  def experiment_params
    params.require(:experiment).permit(:title, :description, :equipment, :procedure, :observations, :results, :conclusion, :researcher_id, :proposal_id)
  end

end

app/views/experiments/edit.html.erb
<div class="row">
  <div class="span4 well">
    <%= form_for :experiment, url: proposal_experiment_path, method: :patch do |f| %>
      <% if @experiment.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@experiment.errors.count, "error") %> prohibited this article from being saved:
          </h2>
          <ul>
            <% @experiment.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
        <fieldset>
          <legend>Edit Experiment</legend>
            <%= f.hidden_field :researcher_id, :value => session[:user_id] %>
          <div class="control-group">
            <%= f.label :title, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :title, size: '100x2' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :description, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :description, size: '100x4' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :equipment, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :equipment, size: '100x4' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :procedure, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :procedure, size: '100x8' %>
            </div>
          </div>

          <div class="form-actions">
            <%= f.submit :class => "btn btn-primary" %>
          </div>
        </fieldset>
    <% end %>
  </div>
</div>

app/views/experiments/index.html.erb
<h1><%= @proposal.title %></h1>
<h3>Current Experiments</h3>
  <% @experiments.each do |experiment| %>
    <h4><%= experiment.title %></h4>
    <p>Stage: <%= experiment.current_stage %></p>
    <p>Title: <%= experiment.title %></p>
    <p>Description: <%= experiment.description %></p>
  <% end %>

app/views/experiments/new.html.erb
<h2><%= @proposal.title %></h2>
<div class="row">
  <div class="span4 well">
    <%= form_for @experiment, url: proposal_experiments_path do |f| %>
        <fieldset>
          <legend>Experiment Form</legend>
            <%= f.hidden_field :researcher_id, :value => session[:user_id] %>
          <div class="control-group">
            <%= f.label :title, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :title, size: '100x2' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :description, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :description, size: '100x4' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :equipment, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :equipment, size: '100x4' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :procedure, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :procedure, size: '100x8' %>
            </div>
          </div>

          <div class="form-actions">
            <%= f.submit :class => "btn btn-primary" %>
          </div>
        </fieldset>
    <% end %>
  </div>
</div>

app/views/experiments/show.html.erb
<h1><%= @experiment.title %></h1>

<div class="row well">
  <div class='col-md-3 col-md-offset-1'>
    <h3>Proposal Title</h3>
      <%= @proposal.title %>
    <h3>Stage</h3>
      <%= @experiment.current_stage.capitalize %><br>
      <progress max="100" value="<%= @experiment.progress %>"></progress>
  </div>
  <div class='col-md-5'>
    <h3>Description</h3>
      <%= @experiment.description %>
  </div>
  <div class='col-md-3'>
    <% if session[:user_id] == @experiment.researcher_id %>
      <p class='button'>
        <%= link_to 'Edit', edit_proposal_experiment_path %>
      </p>
      <p class='button'>
        <%=   link_to 'Delete', proposal_experiment_path,
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>
  </div>
</div>

    <h3>Equipment</h3>
    <ul class='list-unstyled'>
      <% @experiment.equipment.split(", ").each do |tool| %>
        <li><%= tool %></li>
      <% end %>
    </ul>


  <div id="equipment_comments">
    <%= render :partial => "comments/index_equipment.html.erb", :collection => @equipment_comments, as: :equipment_comments  %>
  </div>
  <div class = 'experiment_comment_box'></div>

<br>
<div id="equipment_comments">
  <%= render :partial => "comments/index_equipment.html.erb", :collection => @equipment_comments, as: :equipment_comments  %>
</div>
<button class='experiment_comment_button btn btn-default'>Add Comment</button>
<div class = 'experiment_comment_box'>

    <%= render :partial => "comments/form_equipment.html.erb" %>
  <button class='cancel_experiment_comment btn btn-default'>Cancel</button>
</div>


<h3>Procedure</h3>
  <%= @experiment.procedure %>
<div id="procedure_comments">
  <%= render :partial => "comments/index_procedure.html.erb", :collection => @procedure_comments, as: :comments %>
</div>
<br>
<button class='experiment_comment_button btn btn-default'>Add Comment</button>
<div class = 'experiment_comment_box'>
  <%= render :partial => "comments/form_procedure.html.erb" %>
<button class='cancel_experiment_comment btn btn-default'>Cancel</button>
</div>
<br>

<h3>Observations</h3>

<div class="observations_index">
  <% @observations.each do |observation| %>
  <%= render :partial => "observations/index.html.erb", :locals => {observation: observation, comments: observation.comments} %>
<% end %>
</div>
<br>
<button class="toggle_observations_box btn btn-default">Add Observation</button>
<div id="observations_form">
  <%= form_for [@proposal, @experiment, @observation], url: "/proposals/#{@proposal.id}/experiments/#{@experiment.id}/observations", :method => :post do |f| %>
    <%= f.text_area :content, size: "160x3" %>
    <div class="form-actions">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
<% end %>
</div>


<h3>Results</h3>
  <%= @experiment.results %>
<div id="results_comments">
<%= render :partial => "comments/index_results.html.erb", :collection => @results_comments, as: :comments %>
</div>
<button class='experiment_comment_button btn btn-default'>Add Comment</button>
<div class = 'experiment_comment_box'>
  <%= render :partial => "comments/form_results.html.erb" %>
  <button class='cancel_experiment_comment btn btn-default'>Cancel</button>
</div>


<h3>Conclusion</h3>
  <%= @experiment.conclusion %>
<div ="conclusion_comments">
  <%= render :partial => "comments/index_conclusion.html.erb", :collection => @conclusion_comments, as: :comments %>
</div>
<br>
<button class='experiment_comment_button btn btn-default'>Add Comment</button>
<div class = 'experiment_comment_box'>
  <%= render :partial => "comments/form_conclusion.html.erb" %>
  <button class='cancel_experiment_comment btn btn-default'>Cancel</button>
</div>
<br>
<br>
<br>