config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :proposals do
    resources :experiments do
      resources :observations
    end
  end

  # get '/proposals/:proposal_id' => 'proposals#show', as: 'proposal'
  get '/proposals/:proposal_id/experiments/:experiment_id' => 'experiments#show', as: 'experiment'


  post '/proposals/:proposal_id/comments' => 'comments#create', as: 'proposal_comments'
  post '/proposals/:proposal_id/experiments/:experiment_id/comments' => 'comments#create', as: 'experiment_comment'
  post '/proposals/:proposal_id/experiments/:experiment_id/observations/:observation_id/comments' => 'comments#create', as: 'observation_comment'

  get 'sessions/new'

  post 'sessions/create'

  get 'sessions/destroy'

  root 'proposals#index'

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to  :faculty, class_name: :User
  has_many    :comments, as: :commentable
  has_many    :experiments
  has_many :observations

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("department like ?", "%#{query.capitalize}%")
  end

end

app/controllers/concerns/proposals_controller.rb
class ProposalsController < ApplicationController
  respond_to :html, :js

  def show
    @proposal = Proposal.find(params[:id])
    @comments = @proposal.comments
    @comment = Comment.new
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  respond_to :html, :js

  before_filter :authorize

  def index
    @current_user = User.find_by(id: session[:user_id])
    if params[:search]
      @proposals = Proposal.search(params[:search].capitalize).order("created_at DESC")
    else
      @proposals = Proposal.order("created_at DESC")
    end
  end

  def new
    @proposal = Proposal.new
    @current_user = User.find_by(:id => session[:user_id])
    render :file => "/public/500.html", :status => 500 unless @current_user.is_faculty?
  end

  def create
    @proposal = Proposal.create!(proposal_params)
    @proposal.faculty = User.find_by(:id => session[:user_id])
    @proposal.save
      if @proposal.valid?
        redirect_to proposal_path(@proposal)
      else
        render 'new'
      end
  end

  def edit
    @proposal = Proposal.find(params[:id])
    @current_user = User.find_by(:id => session[:user_id])
    render :file => "/public/500.html", :status => 500 unless @current_user.id == @proposal.faculty.id
  end

  def update
    @proposal = Proposal.find(params[:id])
    if @proposal.update_attributes(proposal_params)
      redirect_to @proposal
    else
      render 'edit'
    end
  end

  def show
    @current_user = User.find_by(:id => session[:user_id])
    @proposal = Proposal.find(params[:id])
    @proposal_creator = @proposal.faculty
    @comments = @proposal.comments
    @experiments = @proposal.experiments
    @researcher_experiments = @experiments.where(researcher_id: @current_user.id)
    @comment = Comment.new
    @researcher_experiments = @experiments.where(researcher_id: @current_user.id)
  end

  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy
    redirect_to proposals_path
  end

  private

  def proposal_params
    params.require(:proposal).permit(:title, :summary, :hypothesis, :department, :active)
  end
end

app/views/proposals/edit.html.erb
<% if @current_user.id === @proposal.faculty.id %>

<div class="row">
  <div class="span4 well">
    <%= form_for @proposal, url: proposal_path do |f| %>
        <fieldset>
          <legend>Edit Your Proposal</legend>
          <div class="control-group">
            <%= f.label :title, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :title, size: '100x2', placeholder: 'Title' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :department, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :department, size: '40x2', placeholder: 'Department' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :summary, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :summary, size: '100x8', placeholder: 'Summary' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :hypothesis, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :hypothesis, size: '100x8', placeholder: 'Hypothesis' %>
            </div>
          </div>

          <div class="form-actions">
            <%= f.submit :class => "btn btn-primary" %>
          </div>
        </fieldset>
    <% end %>
  </div>
</div>
<% end %>

app/views/proposals/index.html.erb
<div class="container">

<h1>Proposals</h1>
    <% if @current_user && @current_user.role == "faculty" %>
    <%= link_to "Submit a New Proposal", new_proposal_path, :class => "btn btn-primary"  %>
    <% end %>

  <div class="row">
    <div class='col-md-3 col-md-offset-1'>
      <h3>Department</h3>
    </div>
    <div class='col-md-8 col-offset-1'>
      <h3>Proposal</h3>
    </div>
  </div>
  <% @proposals.each do |proposal| %>
  <div class="container">
    <div class="row">
      <div class='col-md-1 star'>
        <br>
        <% if proposal.faculty == current_user %>
          <i class='glyphicon glyphicon-star'></i>
        <% end %>
      </div>
      <div class='col-md-3'>
        <br>
       <h4 class="proposal-department"><%= link_to proposal.department, root_path %></h4>
        </div>

      <div class='col-md-8'>
        <h2><%= link_to proposal.title, proposal_path(proposal) %></h2>
        <p>Posted on: <%= proposal.created_at.strftime("%b %d, %Y") %></p>
        <p>Summary: <%= proposal.summary %></p>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/proposals/new.html.erb
<% if @current_user.is_faculty? %>

<div class="row">
  <div class="span4 well">
    <%= form_for @proposal, url: proposals_path do |f| %>
        <fieldset>
          <legend>Submit New Proposal</legend>
          <div class="control-group">
            <%= f.label :title, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :title, size: '100x2' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :department, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :department, size: '100x2' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :summary, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :summary, size: '100x8' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :hypothesis, :class => "control-label" %>
            <div class="controls">
              <%= f.text_area :hypothesis, size: '100x8' %>
            </div>
          </div>

          <div class="form-actions">
            <%= f.submit :class => "btn btn-primary" %>
          </div>
        </fieldset>
    <% end %>
  </div>
</div>
<% end %>

app/views/proposals/show.html.erb
<div class="container">
  <div class='row well well-lg'>
    <h1><%= @proposal.title %></h1>
    <p>Submitted by: <%=  @proposal.faculty.name %> </p>
    <p>Summary: <%=  @proposal.summary %> </p>
    <p>Hypothesis: <%=  @proposal.hypothesis %> </p>
    <br>
    <% if @current_user && @current_user.id === @proposal_creator.id  %>
      <%= link_to "Edit", edit_proposal_path  %> | <%= link_to "Delete", proposal_path(@proposal), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %>
  </div>
  <div class='container'>
    <ul class='list-unstyled'>
      <h2>Experiments</h2>
      <% if @experiments %>
        <% @experiments.each do |experiment| %>
          <li>
            <h3><%= link_to experiment.title, experiment_path(@proposal, experiment) %></h3>
            <p><%= experiment.researcher.name %></p>
            <p><%= experiment.description %> </p>
            <br>
          </li>
          <li class='divider'></li>
        <% end %>
    </ul>
    <% end %>
    <h2>Comments</h2>
    <br>
    <div class='container well'>
      <%= render :partial => "comments/formProposal.html.erb" %>
      <%= render :partial => "comments/index.html.erb" %>
    </div>
  </div>
<% end %>

</div>
  <% if @current_user && @current_user.is_researcher? %>
    <%= link_to "New Experiment", new_proposal_experiment_path(@proposal.id), :class => "btn btn-primary"  %>
    <ul>
      <% @researcher_experiments.each do |experiment| %>
      <li>
        <h3><%= link_to experiment.title, experiment_path(@proposal, experiment) %></h3>
        <p><%= experiment.researcher.name %></p>
        <p><%= experiment.description %> </p>
        <br>
      </li>
      <% end %>
    </ul>

  <% end %>
  <br>
</div>