config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :proposals do
    resources :experiments do
      resources :observations
    end
  end

  # get '/proposals/:proposal_id' => 'proposals#show', as: 'proposal'
  get '/proposals/:proposal_id/experiments/:experiment_id' => 'experiments#show', as: 'experiment'


  post '/proposals/:proposal_id/comments' => 'comments#create', as: 'proposal_comments'
  post '/proposals/:proposal_id/experiments/:experiment_id/comments' => 'comments#create', as: 'experiment_comment'
  post '/proposals/:proposal_id/experiments/:experiment_id/observations/:observation_id/comments' => 'comments#create', as: 'observation_comment'

  get 'sessions/new'

  post 'sessions/create'

  get 'sessions/destroy'

  root 'proposals#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UftResearchPortal</title>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class='navbar navbar-default navbar-static-top'>
  <nav class='container' role='navigation'>
    <div class='navbar-header'>
      <a href='/' class='navbar-brand'>University of Florida | Tallahassee</a>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='.navbar-collapse'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
    </div>
    <ul class='nav navbar-nav navbar-right collapse navbar-collapse'>
      <% if current_user %>
        <li><a class='gold-nav' href="/users/<%= current_user.id %>">Profile</a></li>
        <li><a class='gold-nav' href="/sessions/destroy">Log Out</a></li>
      <% else %>
        <li><a class='gold-nav' href="/sessions/new">Log In</a></li>
        <li><a class='gold-nav' href="/users/new">Register</a></li>
      <% end %>
    </ul>
        <div id="search_bar">
          <%= form_tag(proposals_path, :method => "get", class: "navbar-form")do %>
          <span class="input-append">
            <button class="btn btn-primary pull-right" type="submit">Search</button>
            <%= text_field_tag :search, params[:search], class: "span2 pull-right", placeholder: "Search By Department" %>
          </span>
          <% end %>
        </div>

  </nav>
  </header>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>